#!/usr/bin/env python3
"""Write in-repo IT 402 chapter JSON (20 chapters, same schema as other subjects)."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "site" / "content" / "chapters" / "information-technology"


def ch(**kwargs):
    kwargs.setdefault("visual", [])
    kwargs.setdefault("formulas", [])
    kwargs.setdefault("steps", [])
    kwargs.setdefault("tricks", [])
    kwargs.setdefault("mistakes", [])
    kwargs.setdefault("task", [])
    kwargs.setdefault("onepager", [])
    return kwargs


def qa(t, m, q, a):
    return {"t": t, "m": str(m), "q": q, "a": a}


def mcq(q, a):
    return {"q": q, "a": a}


CHAPTERS = [
    ch(
        id="ch01-communication-skills",
        num=1,
        title="Communication Skills–II",
        unit="pa",
        unit_name="Part A · Employability Skills",
        weight="2 marks",
        short="Methods, feedback, barriers, 7 Cs and basic writing skills.",
        lede="The complete study cycle for Unit 1: methods of communication, the cycle with feedback, barriers, the 7 Cs and basic writing skills — book-style Q&A with hidden answers.",
        lens=[
            "**2 marks inside the 10-mark Part A.** Mostly MCQ plus one short written answer.",
            "Learn the **7-step cycle**, the **7 Cs** and one example each of verbal / non-verbal / visual.",
        ],
        visual=[
            {"t": "Sender", "s": "encodes the idea"},
            {"t": "Message", "s": "via a channel"},
            {"t": "Receiver", "s": "decodes meaning"},
            {"t": "Feedback", "s": "closes the loop"},
        ],
        concepts=[
            "**1. Communication** is the transfer of information, ideas or feelings between a sender and a receiver through a medium, with **feedback** completing the loop.",
            "**2. Communication cycle (draw this in a 2-marker):** Sender → Encoding → Message → Channel → Decoding → Receiver → Feedback.",
            {
                "table": {
                    "head": ["Method", "Means", "Example"],
                    "rows": [
                        ["Verbal – Oral", "Spoken words", "Phone call, meeting, speech"],
                        ["Verbal – Written", "Written words", "Email, letter, report, notice"],
                        ["Non-verbal", "Body, voice, space", "Smile, posture, eye contact, tone"],
                        ["Visual", "Pictures and signs", "Charts, maps, traffic signals, logos"],
                    ],
                }
            },
            "**3. Feedback** is the receiver's response. Good feedback is **descriptive, specific, timely and constructive**. It is called the lifeline because it confirms understanding and corrects errors early.",
            "**4. Barriers:** physical (noise, distance), linguistic (jargon, another language), cultural (gesture meanings), emotional (anger), perceptual, organisational, interpersonal.",
            "**5. 7 Cs of effective communication:** Clear, Concise, Concrete, Correct, Coherent, Complete, Courteous.",
            "**6. Basic writing skills.** A **sentence** has a subject and a predicate. A **phrase** is a group of words without a finite verb. Kinds of sentences: declarative, interrogative, imperative, exclamatory. Parts of speech: noun, pronoun, verb, adjective, adverb, preposition, conjunction, interjection, article. **Articles:** a / an / the. A paragraph starts with a **topic sentence**, then supporting details, then a close.",
            "**7. Paralanguage** is *how* the voice sounds — tone, pitch, speed, pauses. Book fact often quoted: words 7%, voice 38%, body 55%.",
        ],
        formulas=["7 Cs: Clear · Concise · Concrete · Correct · Coherent · Complete · Courteous"],
        tricks=[
            "- 7 Cs mnemonic: **Can Cows Chew Cold Corn Cob Candy?**",
            "- Cycle order: **SEMC DRF** — Sender, Encoding, Message, Channel, Decoding, Receiver, Feedback.",
            "- Non-verbal is the **easiest** method — it needs no language or literacy.",
        ],
        mistakes=[
            "- Writing only verbal/non-verbal and skipping the **oral vs written** split.",
            "- Mixing up **encoding** (sender) and **decoding** (receiver).",
            "- Forgetting an **example** in a 2-marker — the example carries half the marks.",
        ],
        qa=[
            qa("S", 2, "Enlist the different methods of communication.",
               "** (1) Verbal** — oral (speech, phone, meeting) + written (letter, email, report). **(2) Non-verbal** — expressions, gestures, posture, eye contact, tone. **(3) Visual** — charts, maps, signals, posters, videos."),
            qa("S", 2, "Which is the easiest method of communication and why?",
               "**Non-verbal** is the easiest — it needs no language or literacy. Gestures, expressions and tone are understood naturally and work across languages."),
            qa("S", 2, "What is feedback? Why is it called the lifeline of communication?",
               "Feedback is the receiver's response flowing back to the sender. It is the lifeline because it (1) confirms the message was understood and (2) corrects errors early — completing the two-way loop."),
            qa("S", 2, "Explain any two Cs of effective communication with examples.",
               "(1) **Clear** — simple, exact message (“Submit the file by Friday 5 pm”). (2) **Courteous** — polite words (“please”, “thank you”, “sorry for the delay”)."),
            qa("L", 4, "Discuss in detail the verbal method of communication.",
               ["Verbal = communication using **words**, in two forms.",
                "**Oral** (speech, phone, meeting): fast, instant feedback; no permanent record.",
                "**Written** (letter, email, report): permanent proof, re-readable, formal; slower, needs literacy.",
                "Use oral for urgent/personal matters, written when a record is needed."]),
            qa("L", 4, "Explain any four barriers to communication with one example and one measure each.",
               ["(1) **Physical** — class noise → quiet room, working mic.",
                "(2) **Linguistic** — French manual → simple words + visuals.",
                "(3) **Cultural** — a thumbs-up is rude in some places → learn customs.",
                "(4) **Emotional** — anger blocks listening → stay calm, choose the right time."]),
            qa("A", 3, "Riya messages her team “do it soon”. Identify the violated C and rewrite the message correctly.",
               "Violates **Clear** (vague, no deadline) and **Complete** (no what/when). Rewrite: “Please submit the sales sheet by Friday 5 pm on email.” — now clear, complete and courteous."),
            qa("A", 3, "A team leader’s juniors look confused by his technical jargon. What two steps should he take?",
               "(1) Replace jargon with simple words and show a chart (linguistic barrier). (2) Pause, ask “any doubts?”, and paraphrase replies (feedback + active listening)."),
            qa("C", 4, "Read and answer:\n\nAmit presents with zero eye contact, 40 text-packed slides in 10 minutes, and says “no questions, I am getting late”. The manager understands nothing.\n\n(a) Identify four communication mistakes.\n(b) Suggest four fixes.",
               ["(a) No eye contact (poor non-verbal) • overloaded slides (not concise) • too fast (not clear) • no questions (blocks feedback).",
                "(b) Eye contact + open posture • max 10 slides, one idea each • slow, clear speech • invite questions and summarise."]),
            qa("C", 4, "Read and answer:\n\nFor the school fest, Class X puts up posters at shops, announces on a loudspeaker, and the principal sends a written notice to parents.\n\n(a) Name the three methods used.\n(b) Why is combining them better than one?",
               ["(a) Posters = **visual**; loudspeaker = **oral/verbal**; notice = **written**.",
                "(b) Visual attracts, oral spreads fast, written is proof — together they cover more audiences with both speed and a record."]),
        ],
        mcq=[
            mcq("Which part of communication converts an idea into words or signs? (a) Receiving (b) Encoding (c) Decoding (d) Feedback",
                "**(b) Encoding.** Encoding prepares the sender's idea as a message; decoding interprets it."),
            mcq("A loud generator prevents a worker from hearing instructions. The barrier is: (a) linguistic (b) cultural (c) physical (d) emotional",
                "**(c) Physical** — environmental noise blocks the message."),
            mcq("Which of the 7 Cs means “to the point, no extra words”? (a) Clear (b) Concise (c) Concrete (d) Courteous",
                "**(b) Concise.**"),
            mcq("“An honest boy” takes which article? (a) a (b) an (c) the (d) no article",
                "**(b) an** — use *an* before a vowel **sound**; h is silent in honest."),
            mcq("A student's puzzled expression after an explanation is: (a) written encoding (b) non-verbal feedback (c) a channel (d) a language rule",
                "**(b) Non-verbal feedback.**"),
            mcq("Which sentence is complete? (a) Do that work. (b) The form is important. (c) Submit the signed form to Room 4 by Friday noon. (d) Submit it soon.",
                "**(c)** — task, place and deadline are all present."),
            mcq("Paralanguage refers to: (a) body posture only (b) charts and maps (c) tone, pitch and speed of voice (d) grammar rules",
                "**(c) Tone, pitch and speed of voice.**"),
            mcq("The easiest method of communication is: (a) written (b) oral (c) non-verbal (d) email",
                "**(c) Non-verbal** — needs no literacy."),
        ],
        trend="One 2-mark on methods, 7 Cs or feedback, plus 1-mark MCQs on barriers and articles.",
        onepager=[
            "- Methods: verbal (oral + written), non-verbal, visual.",
            "- Cycle: Sender → Encoding → Message → Channel → Decoding → Receiver → Feedback.",
            "- 7 Cs: Clear Concise Concrete Correct Coherent Complete Courteous.",
            "- Good feedback: descriptive, specific, timely, constructive.",
        ],
        task=["Write a formal email to the principal requesting one day's leave. Subject, greeting, 3-line body, sign-off — that is written communication plus courtesy."],
    ),
    ch(
        id="ch02-self-management-skills",
        num=2,
        title="Self-Management Skills–II",
        unit="pa",
        unit_name="Part A · Employability Skills",
        weight="3 marks",
        short="Stress, self-awareness, self-motivation, self-regulation, time and SMART goals.",
        lede="The highest-scoring employability unit. Lists plus one workplace example cover almost every question.",
        lens=["**3 marks.** Stress symptoms, SMART goals and time-management steps are the usual asks.",
              "Always add a **workplace example** — a data-entry operator under a deadline is enough."],
        concepts=[
            "**1. Self-management** is the ability to control one's emotions, thoughts and behaviour and to work towards goals without constant supervision.",
            "**2. Stress** is the body's response to pressure. **Eustress** is positive (a deadline that focuses you); **distress** is harmful. Symptoms: headache, fast heartbeat, irritability, poor sleep, missed errors.",
            "**3. Stress management:** deep breathing, short breaks, exercise, talking to someone, breaking work into chunks, saying no to extra load, sleep and a hobby.",
            "**4. Self-awareness** is knowing your strengths, weaknesses, values and emotions. Tools: SWOT, feedback from others, a journal.",
            "**5. Self-motivation** is working without being pushed. Intrinsic (interest, pride) lasts longer than extrinsic (marks, money).",
            "**6. Self-regulation** is managing impulses — staying calm, delaying gratification, following rules.",
            "**7. Time management:** list tasks, set priorities (urgent/important), use a timetable, avoid multitasking, finish one chunk, review at the end of the day.",
            "**8. SMART goals:** Specific, Measurable, Achievable, Realistic/Relevant, Time-bound. “Type 30 invoices without error by 5 pm Friday” is SMART; “do better” is not.",
        ],
        tricks=["- SMART → **S**pecific **M**easurable **A**chievable **R**ealistic **T**ime-bound.",
                "- Urgent vs important: exam tomorrow is both; scrolling is neither."],
        mistakes=["- Writing SMART expansions in the wrong order.",
                  "- Treating all stress as bad — eustress is useful.",
                  "- Giving no example in a 3-marker."],
        qa=[
            qa("S", 2, "What is self-management? Give two of its benefits.",
               "Controlling one's emotions, thoughts and behaviour to reach goals. Benefits: better work quality, less stress, meeting deadlines, less need for supervision."),
            qa("S", 2, "Differentiate eustress and distress with one example each.",
               "**Eustress** is helpful pressure — a timed practical that makes you focus. **Distress** is harmful — so much overtime that errors increase and sleep is lost."),
            qa("L", 4, "Explain SMART goals with a data-entry example.",
               "Specific (which file), Measurable (how many records), Achievable (within skill), Realistic (hours available), Time-bound (by 5 pm). Example: “Enter 80 customer rows in Calc with zero blanks by 4 pm today.”"),
            qa("A", 3, "Meera has three tasks: a 5 pm file, a messy desk, and a social-media reel. Using urgent/important, what should she do first and why?",
               "The 5 pm file is urgent and important — do it first. The desk is important but not urgent — schedule it. The reel is neither — drop it until the file is in."),
            qa("C", 4, "Read and answer:\n\nRavi’s hands shake before every practical, he skips breakfast and then makes typing errors.\n\n(a) Name the type of stress.\n(b) List four management steps.\n(c) Write one SMART goal for his next practical.",
               ["(a) Distress — it is harming performance.",
                "(b) Breakfast, 4–7 breathing, a 5-minute practice file, a checklist, sleep 7 hours.",
                "(c) “Complete the Base table of 10 records with primary key set, in 25 minutes, with zero errors, on Friday.”"]),
        ],
        mcq=[
            mcq("SMART: the M stands for: (a) Magical (b) Measurable (c) Maximum (d) Monthly", "**(b) Measurable.**"),
            mcq("A hobby after study is mainly: (a) a waste (b) a stress-management method (c) self-employment (d) a barrier", "**(b) a stress-management method.**"),
            mcq("Knowing your own strengths is: (a) self-awareness (b) encoding (c) a physical barrier (d) green skill", "**(a) self-awareness.**"),
            mcq("Which goal is SMART? (a) I will study more (b) I will type 40 correct rows in Calc by 3 pm (c) I will become famous (d) I will try", "**(b).**"),
        ],
        trend="SMART expansion and two stress-management methods appear almost every sample paper.",
        onepager=["- Self-management = control of emotion + behaviour toward a goal.",
                  "- Eustress helps; distress harms.",
                  "- SMART: Specific Measurable Achievable Realistic Time-bound.",
                  "- Time: list → prioritise → one chunk → review."],
        task=["Write three SMART goals for this week: one for theory, one for a LibreOffice file, one for sleep."],
    ),
    ch(
        id="ch03-ict-skills",
        num=3,
        title="ICT Skills–II",
        unit="pa",
        unit_name="Part A · Employability Skills",
        weight="1 mark",
        short="Operating system, files and folders, and basic care of a computer.",
        lede="One mark, almost all MCQ. File, folder, recycle bin and care-of-computer lists are enough.",
        lens=["**1 mark.** Definitions and “which of the following” items.",
              "Know **OS functions**, **file vs folder**, and **three care tips**."],
        concepts=[
            "**1. ICT** is Information and Communication Technology — hardware, software and networks used to create, store and share information.",
            "**2. Operating system (OS)** is system software that manages hardware and lets you run programs. Examples: Windows, Linux, macOS, Android. Functions: start the computer, manage files, memory, devices and security, provide a user interface.",
            "**3. File** = a named collection of data (report.odt). **Folder** = a container for files and other folders. Use short, meaningful names and extensions (.odt, .ods, .odb, .jpg).",
            "**4. Care of computer:** keep it dust-free, don't eat or drink near it, use a surge protector, shut down properly, update antivirus, don't install unknown software, backup important files.",
            "**5. Maintenance:** disk cleanup, defragment (HDD), update OS, scan for malware, keep vents clear so the machine does not overheat.",
        ],
        tricks=["- File has an **extension**; a folder does not need one.",
                "- OS = the **manager** of the machine, not an application like Writer."],
        mistakes=["- Calling Writer an operating system.",
                  "- Saving everything on the Desktop with names like `final2(1).odt`."],
        qa=[
            qa("S", 1, "What is an operating system? Give two examples.",
               "System software that manages hardware and runs programs. Examples: Windows, Linux, Android."),
            qa("S", 2, "Differentiate a file and a folder with one example each.",
               "A **file** stores data (`marks.ods`). A **folder** stores files and other folders (`Class10/IT/`)."),
            qa("A", 3, "Amit eats chips over the keyboard and never shuts the PC down. List three risks and three care steps.",
               "Risks: crumbs jam keys, oil damage, overheating, data loss. Care: no food/drink, proper shutdown, dust-free vents, surge protector, backups."),
            qa("C", 4, "Read and answer:\n\nMeera’s project file vanished after a power cut. She had saved only on the Desktop as `aaa.odt`.\n\n(a) Two file-management mistakes.\n(b) Two care/maintenance steps that would have helped.",
               ["(a) No backup; a meaningless file name; Desktop-only copy.",
                "(b) Surge protector / UPS; Save As into a named folder; weekly backup on a pen drive or cloud."]),
        ],
        mcq=[
            mcq("Which is an OS? (a) LibreOffice Writer (b) Chrome (c) Linux (d) Calc", "**(c) Linux.**"),
            mcq("`.ods` is usually: (a) a Writer file (b) a Calc spreadsheet (c) a Base database (d) an image", "**(b) a Calc spreadsheet.**"),
            mcq("The Recycle Bin is used to: (a) speed up RAM (b) store deleted files until emptied (c) install an OS (d) scan viruses", "**(b).**"),
            mcq("A computer should be shut down: (a) by pulling the plug (b) using the OS shutdown command (c) by holding the monitor button (d) never", "**(b).**"),
        ],
        trend="One MCQ on OS vs application, or on file/folder/care of computer.",
        onepager=["- OS manages hardware and programs.",
                  "- File = data; folder = container.",
                  "- Care: dust, no food, surge protector, shutdown, antivirus, backup."],
        task=["Create a folder `IT402/PartB` with three empty files `writer.odt`, `calc.ods`, `base.odb` and a one-line README."],
    ),
    ch(
        id="ch04-entrepreneurial-skills",
        num=4,
        title="Entrepreneurial Skills–II",
        unit="pa",
        unit_name="Part A · Employability Skills",
        weight="3 marks",
        short="Who an entrepreneur is, qualities, functions, myths and role in society.",
        lede="Definition plus four qualities plus one myth — that is the whole 3-mark answer.",
        lens=["**3 marks.** Qualities of an entrepreneur and “role in society” rotate.",
              "Always add a **small Indian example** (a local bakery, a tutoring app)."],
        concepts=[
            "**1. Entrepreneur** — a person who spots a need, takes a risk, organises resources and starts a business to earn profit and create value.",
            "**2. Entrepreneurship** is the process of creating and running that venture.",
            "**3. Qualities:** initiative, risk-taking, creativity, perseverance, self-confidence, leadership, problem-solving, honesty, hard work.",
            "**4. Functions:** identify opportunity, arrange land/labour/capital, hire and lead, take decisions, bear risk, innovate, market the product.",
            "**5. Myths:** “entrepreneurs are born, not made”; “you need a huge amount of money”; “it is only for the highly educated”; “failure means the person is useless”. All false — skills can be learned, many start small, failure is data.",
            "**6. Role in society:** jobs, new products, use of local resources, wealth, solving local problems (waste, transport, tuition).",
            "**7. Types (brief):** small business, scalable start-up, social entrepreneur (profit is not the only aim).",
        ],
        tricks=["- Quality vs function: quality is a **trait** (perseverance); function is a **job** (arrange capital).",
                "- Myth answers always start with **False**, then the correction."],
        mistakes=["- Calling every shopkeeper an entrepreneur without the risk/innovation idea.",
                  "- Listing qualities with no example."],
        qa=[
            qa("S", 2, "Who is an entrepreneur? Give two qualities.",
               "A person who spots a need, takes a risk and organises resources to start a venture. Qualities: initiative and perseverance (or creativity, self-confidence)."),
            qa("S", 2, "State two myths about entrepreneurship and correct them.",
               "(1) “Born, not made” — skills can be learned. (2) “Needs huge capital” — many start with a small idea and grow."),
            qa("L", 4, "Explain four functions of an entrepreneur with a bakery example.",
               "Identify demand for fresh bread; arrange shop, oven and staff; take the risk of unsold stock; market via samples and a board; keep accounts. Each function maps to one quality: opportunity-spotting, organising, risk-taking, selling."),
            qa("A", 3, "Neha notices students waiting 40 minutes for a shared printer. She starts a paid print-and-bind desk. Which entrepreneurial qualities is she using?",
               "Opportunity-spotting, initiative, risk-taking (she invests in a printer), problem-solving and customer focus."),
            qa("C", 4, "Read and answer:\n\nA poster says “Only rich, highly educated people can start a business.”\n\n(a) Name the myth.\n(b) Give two counter-examples from daily life.\n(c) State two roles of entrepreneurship in society.",
               ["(a) Myth of huge capital / only the highly educated.",
                "(b) A tiffin service from a home kitchen; a tuition class in a garage.",
                "(c) Jobs, new products, local resources used, local problems solved."]),
        ],
        mcq=[
            mcq("An entrepreneur primarily: (a) avoids all risk (b) takes calculated risk to create value (c) only works for a salary (d) copies without a customer", "**(b).**"),
            mcq("Which is a quality, not a function? (a) arranging capital (b) perseverance (c) hiring staff (d) marketing", "**(b) perseverance.**"),
            mcq("A social entrepreneur mainly aims to: (a) ignore people (b) solve a social problem, not only maximise profit (c) avoid accounts (d) work without a product", "**(b).**"),
            mcq("“Entrepreneurs are born, not made” is: (a) a fact (b) a myth (c) a 7 C (d) an OS function", "**(b) a myth.**"),
        ],
        trend="Qualities + one myth, or role of entrepreneurship in society.",
        onepager=["- Entrepreneur = opportunity + risk + resources + value.",
                  "- Qualities: initiative, risk-taking, creativity, perseverance, confidence.",
                  "- Myths: born-not-made, needs huge money, only for the highly educated.",
                  "- Society: jobs, products, local resources, problem-solving."],
        task=["Pick one problem in your school. Write a 6-line business idea: customer, product, cost, risk, one quality you would need."],
    ),
    ch(
        id="ch05-green-skills",
        num=5,
        title="Green Skills–II",
        unit="pa",
        unit_name="Part A · Employability Skills",
        weight="1 mark",
        short="Sustainable development, green economy and green jobs.",
        lede="One-mark unit. Definition of sustainable development plus two green practices.",
        lens=["**1 mark.** Sustainable development definition is the banker.",
              "Add **reduce, reuse, recycle** and one green job."],
        concepts=[
            "**1. Environment** = the surroundings in which we live — air, water, land, plants, animals and humans.",
            "**2. Sustainable development** meets the needs of the present without compromising the ability of future generations to meet their own needs.",
            "**3. Green economy** is low-carbon, resource-efficient and socially inclusive. Growth does not destroy the environment.",
            "**4. Green skills** are the knowledge and attitudes needed for a sustainable society — saving energy, waste segregation, water conservation, green design.",
            "**5. Green jobs:** solar technician, waste-segregation worker, organic farmer, green-building auditor, bicycle mechanic.",
            "**6. Everyday practices:** switch off unused devices, use both sides of paper, carry a bottle, segregate dry/wet waste, plant trees, use public transport.",
        ],
        tricks=["- Sustainable development = **present + future**, not only “planting trees”.",
                "- 3 Rs: Reduce first (best), then Reuse, then Recycle."],
        mistakes=["- Defining sustainable development as “using no resources”. It is **wise use**, not zero use.",
                  "- Mixing green skills with ICT skills."],
        qa=[
            qa("S", 1, "Define sustainable development.",
               "Development that meets present needs without compromising the ability of future generations to meet their own needs."),
            qa("S", 2, "What are green skills? Give two examples.",
               "Skills that help a person live and work in an environmentally friendly way. Examples: waste segregation, saving electricity, water conservation."),
            qa("A", 3, "A computer lab leaves 20 PCs on overnight. Suggest three green practices and one green skill the lab assistant needs.",
               "Shut down PCs, use sleep mode, switch off AC/lights, enable duplex printing. Skill: energy-conservation habit / e-waste handling."),
            qa("C", 4, "Read and answer:\n\nA factory dumps dye in a river but pays workers well.\n\n(a) Is this sustainable development? Why?\n(b) Name two green-economy changes.\n(c) One green job this town could create.",
               ["(a) No — present wages at the cost of future water and health.",
                "(b) Treat effluent, switch to safer dye, reuse water.",
                "(c) Water-treatment operator or waste-segregation worker."]),
        ],
        mcq=[
            mcq("Sustainable development looks after: (a) only the present (b) only the future (c) present without harming the future (d) only factories", "**(c).**"),
            mcq("The best of the 3 Rs is: (a) Recycle (b) Reuse (c) Reduce (d) Refuse nothing", "**(c) Reduce** — don't create the waste."),
            mcq("A solar-panel technician is: (a) a linguistic barrier (b) a green job (c) an OS (d) a myth", "**(b) a green job.**"),
            mcq("Leaving a PC on overnight mainly wastes: (a) paper (b) electricity (c) toner only (d) nothing", "**(b) electricity.**"),
        ],
        trend="Definition of sustainable development, or one green practice / green job.",
        onepager=["- Sustainable development = present + future.",
                  "- Green economy: low carbon, resource-efficient, inclusive.",
                  "- 3 Rs: Reduce, Reuse, Recycle.",
                  "- Green jobs: solar, waste, organic farming, green buildings."],
        task=["For one school day, list five green actions you actually did (lights, paper, water, waste, travel)."],
    ),
]

# Part B chapters continue in the same list via extend below.

CHAPTERS.extend([
    ch(
        id="ch06-writer-styles",
        num=6,
        title="Introduction to Styles (Writer)",
        unit="writer",
        unit_name="Part B · Digital Documentation (Advanced)",
        weight="part of 8 marks",
        short="Page, paragraph, character, frame, list and table styles in LibreOffice Writer.",
        lede="Styles are the backbone of Unit 1. Fill Format plus custom styles are the practical.",
        lens=["Theory asks **types of styles** and **why styles beat manual formatting**.",
              "Practical: apply Heading 1/2, create a custom style, use Fill Format."],
        concepts=[
            "**1. A style** is a named collection of formatting. Change the style once, every place it is used updates.",
            "**2. Six categories in Writer:** Paragraph, Character, Page, Frame, List (Numbering), Table.",
            "**3. Styles window:** Sidebar → Styles, or `F11`. Filter: All / Applied / Hierarchical / Custom.",
            "**4. Fill Format mode:** click Fill Format, then click paragraphs to paint the same style quickly.",
            "**5. Updating a style:** format one paragraph as you want → right-click the style → **Update Style**.",
            "**6. New style:** right-click in Styles → **New**. Give a name, set font/indents/spacing, OK.",
            "**7. Load styles** from another document or template: Styles menu → **Load Styles** (overwrite / page / numbering options).",
            "**8. Why styles:** consistent look, faster ToC (Headings), smaller files than direct formatting, easy branding.",
        ],
        steps=["1. Open Styles (`F11`).",
               "2. Choose the category (Paragraph for headings).",
               "3. Double-click Heading 1 on the title, Heading 2 on subheadings.",
               "4. To copy, click Fill Format and click each target paragraph.",
               "5. To customise, right-click → New / Modify."],
        tricks=["- Headings must use **Heading styles**, not just Bold 16 pt — otherwise ToC will be empty.",
                "- Character styles change a **few words** inside a paragraph; paragraph styles change the **whole para**."],
        mistakes=["- Building a ToC from manually bolded text.",
                  "- Updating the wrong style and changing the whole document by accident."],
        qa=[
            qa("S", 2, "What is a style in Writer? Name any four categories.",
               "A named set of formatting that can be reused. Categories: Paragraph, Character, Page, Frame, List, Table."),
            qa("S", 2, "What is Fill Format mode?",
               "A Styles-window tool that copies the selected style onto each paragraph (or object) you click, like a format paintbrush."),
            qa("L", 4, "Why should a long report use styles instead of manual formatting?",
               "One change updates every heading; ToC can be generated; the look stays consistent; less chance of mixed fonts; templates become reusable."),
            qa("A", 3, "A 20-page report uses Bold 16 pt for titles. The examiner wants Heading 1 in navy. What should the student do instead of selecting each title?",
               "Create or modify **Heading 1** (navy, size, spacing), then Fill Format / select each title and apply Heading 1. Later, one modify updates all."),
            qa("C", 4, "Read and answer:\n\nNeha’s ToC is empty even though titles look big and bold.\n\n(a) Why?\n(b) Steps to fix it.\n(c) How will this help next time she changes the colour of all headings?",
               ["(a) Titles used direct formatting, not Heading styles.",
                "(b) Apply Heading 1/2, then Insert → Table of Contents.",
                "(c) Modify Heading 1 once — every heading and the ToC pick up the new colour."]),
        ],
        mcq=[
            mcq("Shortcut for the Styles window is usually: (a) F1 (b) F5 (c) F11 (d) F12", "**(c) F11.**"),
            mcq("Which style changes a few words inside a paragraph? (a) Page (b) Character (c) Frame (d) Table", "**(b) Character.**"),
            mcq("Fill Format is used to: (a) insert images (b) paint a style onto many paragraphs (c) mail merge (d) record a macro", "**(b).**"),
            mcq("ToC in Writer is built from: (a) bold text (b) Heading styles (c) page numbers only (d) hyperlinks only", "**(b) Heading styles.**"),
        ],
        trend="Types of styles + advantage of styles; practical is Heading styles + Fill Format.",
        onepager=["- Style = named formatting.",
                  "- Six types: Paragraph, Character, Page, Frame, List, Table.",
                  "- F11, Fill Format, Update Style, New, Load Styles.",
                  "- Headings → ToC."],
        task=["Type a 1-page note with Title, two Heading 1, three Heading 2. Create a custom paragraph style `ExamPoint` (11 pt, 0.5 cm indent) and apply it to body text."],
    ),
    ch(
        id="ch07-writer-images",
        num=7,
        title="Working with Images (Writer)",
        unit="writer",
        unit_name="Part B · Digital Documentation (Advanced)",
        weight="part of 8 marks",
        short="Insert, wrap, arrange, drawing objects, grouping and captions.",
        lede="Practical-heavy. Wrap settings and grouping are the viva favourites.",
        lens=["Expect “how to wrap an image” and “difference between anchor types”.",
              "File work: insert a picture, wrap Optimal, add a caption, group a callout."],
        concepts=[
            "**1. Insert image:** Insert → Image, or drag from a folder, or copy-paste. Keep a copy of the picture with the file if you must move the document.",
            "**2. Anchoring:** To Paragraph (moves with that para), To Character, As Character (like a big letter in the line), To Page (stays on that page).",
            "**3. Text wrap:** None, Before, After, Parallel, Optimal, Through, In Background. **Optimal** is the usual body-text wrap.",
            "**4. Arrangement:** Bring to Front / Send to Back when images overlap.",
            "**5. Drawing toolbar:** lines, arrows, rectangles, callouts, text boxes. Hold Shift for a circle/square.",
            "**6. Grouping:** select several drawing objects (Shift-click) → right-click → **Group**. They move as one.",
            "**7. Crop, resize, rotate** from the Image toolbar. Keep aspect ratio unless the question says otherwise.",
            "**8. Caption:** right-click image → Insert Caption (Figure 1: …). Captions help a Table of Figures.",
        ],
        steps=["1. Insert → Image → choose file.",
               "2. Click the image → Properties / Wrap → Optimal.",
               "3. Anchor To Paragraph.",
               "4. Right-click → Insert Caption.",
               "5. Add an arrow from Drawing; Shift-select + Group."],
        tricks=["- If text jumps wildly, the image is probably **As Character** — change wrap and anchor.",
                "- Grouping works on **drawing objects**, not always on a mixed photo+shape until you convert/careful-select."],
        mistakes=["- Stretching a photo so faces look wide — hold Shift or lock ratio.",
                  "- Saving a document without the image folder when images were linked, not embedded."],
        qa=[
            qa("S", 2, "Name any four text-wrapping options in Writer.",
               "None, Before, After, Parallel, Optimal, Through, In Background (any four)."),
            qa("S", 2, "What does grouping do?",
               "It joins selected drawing objects so they move, resize and copy as a single object."),
            qa("L", 4, "Explain anchoring of images in Writer.",
               "Anchor decides what the image sticks to: **To Paragraph** (moves with the para), **To Character**, **As Character** (in the text line), **To Page** (fixed on that page). Choose To Paragraph + Optimal wrap for reports."),
            qa("A", 3, "An image covers the heading of a report. Which two settings would you change first?",
               "Wrap (Optimal or After) and arrangement (Send to Back) or move the anchor to the correct paragraph."),
            qa("C", 4, "Read and answer:\n\nA student’s picture sits in a huge white box and the caption is not numbered.\n\n(a) Two likely causes.\n(b) Steps to insert a proper Figure caption.\n(c) Why captions help in a long file.",
               ["(a) Wrap = None; image as a huge As-Character object; no Insert Caption used.",
                "(b) Right-click → Insert Caption → category Figure → type the title.",
                "(c) Auto numbering and a Table of Figures."]),
        ],
        mcq=[
            mcq("Optimal wrap means: (a) image hidden (b) text flows in the best way around the image (c) image deleted (d) no caption", "**(b).**"),
            mcq("To move several shapes together: (a) Mail Merge (b) Group (c) Goal Seek (d) Styles F11", "**(b) Group.**"),
            mcq("Inserting a caption is done by: (a) File → New (b) right-click image → Insert Caption (c) Tools → Macros (d) Data → Sort", "**(b).**"),
            mcq("Anchor “As Character” treats the image: (a) as a page background (b) like a character in the line (c) as a hidden file (d) as a style", "**(b).**"),
        ],
        trend="Wrap + anchor, or steps to insert and caption an image.",
        onepager=["- Insert → Image; crop/resize with ratio locked.",
                  "- Wrap: Optimal for body text.",
                  "- Anchor: usually To Paragraph.",
                  "- Caption + Group drawing objects."],
        task=["Insert a school-building photo, wrap Optimal, caption it Figure 1, and draw a labelled arrow to the main gate; group the arrow and label."],
    ),
    ch(
        id="ch08-writer-toc-templates",
        num=8,
        title="ToC, Templates and Track Changes",
        unit="writer",
        unit_name="Part B · Digital Documentation (Advanced)",
        weight="part of 8 marks",
        short="Table of Contents, templates, track changes, comments and mail merge.",
        lede="The rest of Writer. ToC from Heading styles, a template `.ott`, and review tools.",
        lens=["ToC steps and Track Changes on/off are asked every year.",
              "Mail merge: data source + main document + merge fields."],
        concepts=[
            "**1. Table of Contents:** apply Heading 1/2/3 → Insert → Table of Contents and Index → Table of Contents. Update with right-click → **Update Index** after edits.",
            "**2. Template (`.ott`):** a starter document with styles, headers, logos. File → Templates → Save as Template. File → New → Templates to use it.",
            "**3. Track Changes:** Edit → Track Changes → Record. Insertions show as underline, deletions as strike-out. Accept or Reject from the toolbar. Useful when two people edit one file.",
            "**4. Comments:** Insert → Comment (`Ctrl+Alt+C`) for notes in the margin without changing the text.",
            "**5. Mail Merge:** main letter + data source (Calc/Base/CSV) + merge fields (Name, Address) → Print or save letters. Steps: Tools → Mail Merge Wizard, or insert fields then File → Print → Mail Merge.",
            "**6. Advantages of mail merge:** same letter to many people, no retyping, fewer spelling mistakes in names, labels and envelopes too.",
        ],
        steps=["Mail merge:",
               "1. Create the letter in Writer.",
               "2. Connect a data source (Calc sheet with Name, Address columns).",
               "3. Insert merge fields where the name/address should appear.",
               "4. Preview, then output to printer or separate files."],
        tricks=["- Empty ToC ⇒ headings are not Heading styles.",
                "- Track Changes must be **Record On** *before* the other person edits, or you will see no markup."],
        mistakes=["- Saving a template as `.odt` instead of `.ott`.",
                  "- Typing names by hand in 50 letters instead of merge fields."],
        qa=[
            qa("S", 2, "Write the steps to insert a Table of Contents in Writer.",
               "Apply Heading styles → Insert → Table of Contents and Index → Table of Contents → OK. Right-click → Update Index after changes."),
            qa("S", 2, "What is a document template?",
               "A model file (`.ott`) that stores styles, headers and boilerplate so new documents start consistent."),
            qa("L", 4, "Explain mail merge and its advantages.",
               "Mail merge combines a main document with a data source to produce personalised letters. Advantages: speed, accuracy of names, one design for many copies, labels/envelopes."),
            qa("A", 3, "A teacher wants 40 identical permission letters with only the parent name changing. Which Writer feature, and what two files does she need?",
               "Mail merge. She needs the main letter and a data source (Calc column `ParentName`)."),
            qa("C", 4, "Read and answer:\n\nTwo students edit `report.odt`. One deletes a paragraph; the other does not know what changed.\n\n(a) Which tool should have been on?\n(b) How do they accept only some edits?\n(c) When would a Comment be better than changing the text?",
               ["(a) Track Changes → Record.",
                "(b) Review each change → Accept or Reject.",
                "(c) When suggesting, not rewriting — e.g. “please add the figure here”."]),
        ],
        mcq=[
            mcq("Writer templates usually use the extension: (a) .ods (b) .ott (c) .odb (d) .jpg", "**(b) .ott.**"),
            mcq("ToC is updated by: (a) F11 (b) right-click the ToC → Update Index (c) Goal Seek (d) Group", "**(b).**"),
            mcq("Mail merge needs: (a) only an image (b) a main document and a data source (c) only a printer (d) a Base report only", "**(b).**"),
            mcq("Recorded deletions in Track Changes usually appear as: (a) a new page (b) strike-out text (c) a ToC (d) a style", "**(b) strike-out text.**"),
        ],
        trend="ToC steps, template definition, or mail-merge advantages.",
        onepager=["- ToC from Heading 1/2/3; Update Index.",
                  "- Template = .ott with styles.",
                  "- Track Changes: Record, Accept, Reject; Comments for notes.",
                  "- Mail merge = letter + data source + fields."],
        task=["Create a 2-page notes file with headings, insert a ToC on page 1, turn on Track Changes, and make two dummy edits."],
    ),
    ch(
        id="ch09-calc-scenarios-goal-seek",
        num=9,
        title="Scenarios and Goal Seek (Calc)",
        unit="calc",
        unit_name="Part B · Electronic Spreadsheet (Advanced)",
        weight="part of 10 marks",
        short="Data consolidation, subtotals, what-if scenarios, Goal Seek and Solver.",
        lede="The analysis half of Calc. Goal Seek is the one tool you must be able to demo.",
        lens=["**Goal Seek** and **Scenarios** are the theory + practical pair.",
              "Also: Consolidate, Group/Outline, Subtotals."],
        concepts=[
            "**1. Consolidate:** Data → Consolidate. Combines the same layout from several sheets (e.g. four term marks) using Sum/Average. Tick “Link to source data” to auto-update.",
            "**2. Groups and outline:** Data → Group and Outline. Hide detail rows; show only totals.",
            "**3. Subtotals:** sort first, then Data → Subtotals on a column (e.g. subtotal marks by section).",
            "**4. What-if analysis:** change inputs to see outputs. Three tools: Scenarios, Goal Seek, Solver.",
            "**5. Scenarios:** named sets of input cells (Best case, Worst case). Tools → Scenarios. Switching the name swaps the inputs and the formulas recalculate.",
            "**6. Goal Seek:** Tools → Goal Seek. You know the **result** you want; Calc finds the **input**. Example: “What price makes profit = 10000?” Set cell, To value, By changing cell.",
            "**7. Solver:** for many variables and constraints (maximise profit with limits). Heavier than Goal Seek.",
        ],
        steps=["Goal Seek:",
               "1. Click the formula cell (profit).",
               "2. Tools → Goal Seek.",
               "3. Formula cell already filled; type the target in “To value”.",
               "4. “By changing cell” = the input (price).",
               "5. OK — Calc tries values until the target is hit."],
        formulas=["Profit = Revenue − Cost",
                  "Goal Seek: set formula cell → target value → change input cell"],
        tricks=["- Goal Seek needs a **formula** in the set cell. Typing a number there will fail.",
                "- Sort **before** Subtotals or the groups will be wrong."],
        mistakes=["- Mixing up Goal Seek (one input) with Solver (many inputs + constraints).",
                  "- Forgetting to name scenarios, so you cannot switch back."],
        qa=[
            qa("S", 2, "What is Goal Seek in Calc?",
               "A what-if tool: you set the result you want in a formula cell and Calc finds the input value that produces it."),
            qa("S", 2, "What is a scenario?",
               "A named set of values for specified cells so you can switch between cases (best/worst) without retyping."),
            qa("L", 4, "Differentiate Consolidate and Subtotals.",
               "Consolidate **combines several ranges/sheets** into one summary (often another sheet). Subtotals **insert summary rows inside one sorted list** (sum of each group). Consolidate is across blocks; Subtotals is inside a table."),
            qa("A", 3, "A shop wants profit of ₹8,000. Profit is `=B2*B3-B4` (price × qty − cost). Which tool, and which cell is “By changing” if qty and cost are fixed?",
               "Goal Seek. Set cell = profit, To value = 8000, By changing = price (`B2`)."),
            qa("C", 4, "Read and answer:\n\nFour quarterly sheets have the same layout of expenses. The owner wants one yearly total that updates if a quarter changes.\n\n(a) Which tool?\n(b) Two settings to tick/choose.\n(c) Why not just type the four totals by hand?",
               ["(a) Data → Consolidate.",
                "(b) Function Sum; add each range; Link to source data.",
                "(c) Manual totals go stale; a link updates and reduces typing errors."]),
        ],
        mcq=[
            mcq("Goal Seek is on the menu: (a) Insert (b) Tools (c) Format (d) Window", "**(b) Tools.**"),
            mcq("Before Subtotals you must: (a) insert a chart (b) sort the group column (c) record a macro (d) protect the sheet", "**(b) sort.**"),
            mcq("A named best-case / worst-case set of inputs is a: (a) style (b) scenario (c) query (d) template", "**(b) scenario.**"),
            mcq("Consolidate is best when data is: (a) on several similar sheets (b) a single cell (c) an image (d) a Writer ToC", "**(a).**"),
        ],
        trend="Goal Seek steps, or difference between scenario and Goal Seek.",
        onepager=["- Consolidate sheets; Subtotals after sort; Group to hide detail.",
                  "- Scenario = named inputs.",
                  "- Goal Seek: know result, find input.",
                  "- Solver: many variables + constraints."],
        task=["Build Price, Qty, Cost, Profit. Goal Seek profit to 5000 by changing Price. Save two scenarios: Busy Day and Slack Day."],
    ),
    ch(
        id="ch10-calc-macros",
        num=10,
        title="Macros in Spreadsheet",
        unit="calc",
        unit_name="Part B · Electronic Spreadsheet (Advanced)",
        weight="part of 10 marks",
        short="Record, run, and use macros as functions; when not to use them.",
        lede="Recording a macro is a 5-mark practical if you can find the menu under Tools.",
        lens=["Steps to **record and run** a macro, plus one use-case (repeating a format or a formula block).",
              "Security: enable macros only from trusted files."],
        concepts=[
            "**1. A macro** is a recorded sequence of commands. Play it back to repeat the work.",
            "**2. Record:** Tools → Macros → Record Macro → do the steps → Stop Recording → name it → save in the document or My Macros.",
            "**3. Run:** Tools → Macros → Run Macro → pick the name. Or assign it to a button / key.",
            "**4. Use as a function:** some recorded macros can be called from a sheet; in Class 10 the expected skill is record-and-run, not writing BASIC by hand.",
            "**5. Good uses:** apply a school marksheet format, insert a header, convert a column to uppercase, print settings.",
            "**6. Macro security:** Tools → Options → Security → Macro Security. Very high / High / Medium / Low. Use Medium or High; never run macros from unknown people.",
        ],
        steps=["1. Tools → Macros → Record Macro.",
               "2. Perform the actions (format, sort, formula).",
               "3. Stop Recording, give a name.",
               "4. Tools → Macros → Run Macro to test.",
               "5. Optional: assign to a toolbar button."],
        tricks=["- Plan the clicks **before** you press Record — extra clicks get recorded too.",
                "- Save the file as `.ods` with macros enabled; some formats drop macros."],
        mistakes=["- Recording a macro that depends on a **specific cell** when you needed a relative range.",
                  "- Enabling macros on a downloaded file you do not trust."],
        qa=[
            qa("S", 2, "What is a macro? Give one use in Calc.",
               "A saved list of commands that can be replayed. Use: apply the same marksheet formatting every term."),
            qa("S", 2, "Write the menu path to record a macro in Calc.",
               "Tools → Macros → Record Macro, perform the steps, Stop Recording, name the macro."),
            qa("L", 4, "Explain macro security levels and a safe practice for students.",
               "Very High / High / Medium / Low control whether unsigned macros run. Students should keep High or Medium, enable macros only on their own practical files, and never open a macro-enabled sheet from an unknown chat."),
            qa("A", 3, "Every Monday you set print area A1:G40, landscape, header “Weekly Sales”. How does a macro help?",
               "Record those page-setup steps once. Each Monday, Run Macro — one click instead of eight menu steps, fewer missed settings."),
            qa("C", 4, "Read and answer:\n\nA classmate sends `marks.ods` that auto-runs a macro on open.\n\n(a) What should you do first?\n(b) When is a macro a good idea in your own file?\n(c) One limitation of recorded macros.",
               ["(a) Do not enable macros until you trust the source; check Security level.",
                "(b) When the same clicks are repeated often on your own data.",
                "(c) They record extra clicks; they may break if the sheet layout changes."]),
        ],
        mcq=[
            mcq("Macros in Calc are started from: (a) Insert → Image (b) Tools → Macros (c) Data → Sort (d) Format → Cells", "**(b).**"),
            mcq("A macro is: (a) a virus always (b) a recorded command sequence (c) a Heading style (d) a primary key", "**(b).**"),
            mcq("Unknown file asks to enable macros. You should: (a) always click Enable (b) enable only if you trust the source (c) delete LibreOffice (d) turn security to Low forever", "**(b).**"),
            mcq("Best use of a macro: (a) one-time typing of a name (b) repeating a long format every week (c) drawing a circle once (d) writing an essay", "**(b).**"),
        ],
        trend="Record-macro steps and one advantage; security as a 1-mark.",
        onepager=["- Macro = recorded commands.",
                  "- Tools → Macros → Record / Run.",
                  "- Name it; save in the document.",
                  "- Security High/Medium; never unknown files."],
        task=["Record a macro that bolds row 1, adds a yellow background and auto-fits columns A–F. Run it on a new sheet."],
    ),
    ch(
        id="ch11-calc-linking",
        num=11,
        title="Linking Spreadsheet Data",
        unit="calc",
        unit_name="Part B · Electronic Spreadsheet (Advanced)",
        weight="part of 10 marks",
        short="Sheet links, hyperlinks, linking to external files and data from the web.",
        lede="One formula across sheets is the whole idea: `'Sheet2'.A1` or a hyperlink to a file.",
        lens=["Syntax of a sheet reference and Insert → Hyperlink.",
              "External link: `'file:///path/file.ods'#Sheet1.A1` in principle; in the exam they ask the idea, not the URL."],
        concepts=[
            "**1. Same-file sheet link:** `=Sheet2.B3` or `='Term 1'.B3` if the sheet name has a space.",
            "**2. Why link:** one source of truth — change the source, every summary updates.",
            "**3. Hyperlink:** Insert → Hyperlink to a web page, a mail, a file, or a target in this document (a named cell).",
            "**4. Linking to another spreadsheet:** copy cells → Paste Special → Link, or type an external reference. The target file should stay in the same folder for the practical exam.",
            "**5. Data from the web / register:** Insert → Link to External Data (where available) for tables that refresh.",
            "**6. Find broken links:** Edit → Links to External Files (if present) to update or break the link.",
        ],
        formulas=["=Sheet2.A1",
                  "='Marks Term1'.C5",
                  "HYPERLINK(\"https://cbseacademic.nic.in\")"],
        tricks=["- Sheet names with spaces need **single quotes**: `'Term 1'.A1`.",
                "- Absolute `$A$1` still works across sheets: `=Sheet2.$B$3`."],
        mistakes=["- Renaming a sheet after writing formulas without checking — some links break.",
                  "- Emailing only the summary file when it **links** to `data.ods` left on the lab PC."],
        qa=[
            qa("S", 2, "Write a formula that shows cell B4 of sheet Fees on sheet Summary.",
               "`=Fees.B4` or `='Fees'.B4`."),
            qa("S", 2, "What is a hyperlink in Calc?",
               "A clickable link to a web page, file, email or a location in the document, inserted via Insert → Hyperlink."),
            qa("L", 4, "Why is linking sheets better than copy-pasting values for a yearly total?",
               "A link stays live: when a term sheet changes, the year sheet updates. Copy-paste values go stale, cause mismatch, and make auditing harder."),
            qa("A", 3, "Summary sheet must show `Total` from three term sheets named Term1, Term2, Term3, each total in G20. Write the formula.",
               "`=Term1.G20+Term2.G20+Term3.G20`"),
            qa("C", 4, "Read and answer:\n\nA student pastes last month’s numbers into the annual sheet. The teacher later corrects the January file; the annual sheet does not change.\n\n(a) What did the student do wrong?\n(b) How should the cells have been pasted?\n(c) One risk of live links.",
               ["(a) Pasted values, not links.",
                "(b) Paste Special → Link, or a formula to the January sheet.",
                "(c) If the source file is moved/renamed, the link breaks — keep files together."]),
        ],
        mcq=[
            mcq("A sheet name with a space is written as: (a) Term 1.A1 (b) 'Term 1'.A1 (c) Term_only (d) (Term1)A1", "**(b) 'Term 1'.A1.**"),
            mcq("Insert → Hyperlink can open: (a) only images (b) a web page or a file (c) Goal Seek (d) a style", "**(b).**"),
            mcq("Live totals that update when a source sheet changes need: (a) a screenshot (b) a formula/link (c) Track Changes (d) a caption", "**(b).**"),
            mcq("Paste Special → Link is used to: (a) break a file (b) keep a live connection to copied cells (c) record a macro (d) group shapes", "**(b).**"),
        ],
        trend="Write a cross-sheet formula, or advantage of linking vs paste.",
        onepager=["- `=Sheet2.A1` and `'Name with space'.A1`.",
                  "- Hyperlink: web, file, email, internal target.",
                  "- Paste Special → Link for live copies.",
                  "- Keep linked files in one folder."],
        task=["Make sheets Jan, Feb, Year. Year!B2 = Jan!B2+Feb!B2. Change Jan and watch Year update. Add a hyperlink to the CBSE academic site."],
    ),
    ch(
        id="ch12-calc-share-review",
        num=12,
        title="Share and Review a Spreadsheet",
        unit="calc",
        unit_name="Part B · Electronic Spreadsheet (Advanced)",
        weight="part of 10 marks",
        short="Sharing, recording changes, adding comments, comparing and merging sheets.",
        lede="The collaboration half of Calc — same idea as Track Changes in Writer.",
        lens=["Share spreadsheet + record changes is the pair.",
              "Know: comments, compare documents, merge."],
        concepts=[
            "**1. Share spreadsheet:** Tools → Share Spreadsheet. Several people can open it (on a network). Conflicts are resolved when saving.",
            "**2. Record changes:** Edit → Track Changes → Record (wording may be Record Changes). Shows who changed which cell.",
            "**3. Show changes:** Edit → Track Changes → Show. Accept or reject like Writer.",
            "**4. Comments on cells:** Insert → Comment. A small triangle marks the cell. Use for “please check this total”, not for storing the answer itself.",
            "**5. Compare documents:** Edit → Track Changes → Compare Document — against an older copy to see differences.",
            "**6. Merge:** bring another user’s copy back into the shared original.",
            "**7. Protect sheet:** Tools → Protect Sheet so others can edit only unlocked input cells.",
        ],
        tricks=["- Sharing is for **one file, many users**; emailing five copies is how totals diverge.",
                "- Unlock input cells **before** protecting the sheet."],
        mistakes=["- Protecting the sheet with no password written in the practical file — you cannot demo it.",
                  "- Recording changes after the work is already done."],
        qa=[
            qa("S", 2, "How do you share a Calc spreadsheet?",
               "Tools → Share Spreadsheet → enable sharing. Save on a network location the team can open."),
            qa("S", 2, "Why add a comment to a cell instead of changing the value?",
               "A comment suggests or questions without overwriting data; the original number stays until someone decides."),
            qa("L", 4, "Explain recording, showing and accepting changes in Calc.",
               "Turn Record on before editing. Each changed cell is marked. Show lists author, date and old/new value. Accept keeps the new value; Reject restores the old. Compare Document does this against a saved copy."),
            qa("A", 3, "Three lab partners type in three copies of `stock.ods` and the totals disagree. What should they have used?",
               "One shared spreadsheet (or one file with Record Changes + merge), not three independent copies."),
            qa("C", 4, "Read and answer:\n\nA teacher wants students to fill only column B, not the formulas in C.\n\n(a) Which tool?\n(b) Steps.\n(c) How can the teacher see who changed B5?",
               ["(a) Protect Sheet (unlock B first).",
                "(b) Select B → unprotect cells; Tools → Protect Sheet; set password.",
                "(c) Record / Show Changes — author and date on B5."]),
        ],
        mcq=[
            mcq("Share Spreadsheet is under: (a) Insert (b) Tools (c) Format (d) Data", "**(b) Tools.**"),
            mcq("A cell comment is for: (a) hiding formulas forever (b) notes without changing the value (c) Goal Seek (d) styles", "**(b).**"),
            mcq("To allow editing only some cells: (a) Group (b) Protect Sheet after unlocking inputs (c) Consolidate (d) Mail Merge", "**(b).**"),
            mcq("Compare Document is useful when: (a) you have an older copy to diff (b) you need a chart (c) you insert an image (d) you write a ToC", "**(a).**"),
        ],
        trend="Share vs record changes, or protect sheet steps.",
        onepager=["- Tools → Share Spreadsheet.",
                  "- Record / Show / Accept / Reject changes.",
                  "- Insert → Comment.",
                  "- Protect Sheet; unlock inputs first.",
                  "- Compare and merge copies."],
        task=["Protect a marksheet so only the Marks column is editable. Add a comment on a zero mark asking “absent or not entered?”"],
    ),
])

CHAPTERS.extend([
    ch(
        id="ch13-dbms-intro",
        num=13,
        title="Introduction to DBMS",
        unit="dbms",
        unit_name="Part B · Database Management System",
        weight="part of 12 marks",
        short="Data vs information, database, DBMS advantages, keys and types of database.",
        lede="Unit 3 is 12 marks — start here. Definitions are free marks if the wording is tight.",
        lens=["**Data vs information**, **advantages of DBMS**, **primary key** — the opening trio.",
              "Know: field, record, table, database; flat vs relational."],
        concepts=[
            "**1. Data** are raw facts (`Ravi`, `78`). **Information** is processed, useful data (“Ravi scored 78 in IT”).",
            "**2. A database** is an organised collection of related data. A **DBMS** (LibreOffice Base, MySQL) is software to create and manage databases.",
            "**3. Advantages of DBMS:** less redundancy, consistency, sharing, security, backup/recovery, data independence, concurrent use, integrity.",
            "**4. Disadvantages:** cost, training, a single failure can block many users if not backed up.",
            "**5. Building blocks:** **Field** (column, one attribute), **Record** (row), **Table** (entity), **Database** (set of tables).",
            "**6. Keys:** **Primary key** uniquely identifies a record (AdmissionNo). **Composite key** uses two+ fields. **Foreign key** in another table points to a primary key (referential integrity).",
            "**7. Flat file** = one table (Calc). **Relational database** = several related tables (Base) — this is what Unit 3 uses.",
            "**8. Data types (preview):** Text (VARCHAR), Integer, Decimal, Date, Yes/No (Boolean), Memo.",
        ],
        tricks=["- Primary key = **unique + not empty**. Roll number works; student name does not.",
                "- DBMS advantage answers: write **four**, each with a three-word explanation."],
        mistakes=["- Calling Calc a DBMS. Calc is a spreadsheet; Base is the DBMS in this course.",
                  "- Using Name as primary key."],
        qa=[
            qa("S", 2, "Differentiate data and information with an example.",
               "Data are raw facts (42, “Neha”). Information is processed and meaningful (“Neha’s attendance is 42 days”)."),
            qa("S", 2, "What is a primary key? Give one example.",
               "A field (or set of fields) that uniquely identifies each record and cannot be empty. Example: `AdmissionNo` in a Student table."),
            qa("L", 4, "List four advantages of a DBMS over a paper register or a single Calc sheet.",
               "Less duplication; one correction updates all uses; password/security; backup and recovery; many users; validation (integrity). A Calc sheet is easy to duplicate and hard to relate as tables grow."),
            qa("A", 3, "A school stores students in one sheet with teacher phone numbers typed against every student. Two problems, and the DBMS idea that fixes them.",
               "Redundancy (phone typed 40 times) and inconsistency (one row has the old number). Split into Student and Teacher tables with a foreign key."),
            qa("C", 4, "Read and answer:\n\nA clinic keeps patient names in a diary. Two staff write different spellings; a page is lost.\n\n(a) Two problems of this system.\n(b) Two DBMS advantages that help.\n(c) Suggest a primary key.",
               ["(a) Inconsistency, no backup, slow search, redundancy.",
                "(b) Central consistent data, backup/recovery, validation, sharing.",
                "(c) PatientID or a unique registration number — not the name."]),
        ],
        mcq=[
            mcq("Which is information, not raw data? (a) 36 (b) “Amit” (c) “Amit’s temperature is 36 °C” (d) a blank cell", "**(c).**"),
            mcq("LibreOffice Base is: (a) a DBMS (b) an OS (c) a browser (d) a style", "**(a) a DBMS.**"),
            mcq("A good primary key for books is: (a) Title (b) Author (c) ISBN (d) Colour", "**(c) ISBN.**"),
            mcq("A foreign key: (a) deletes the database (b) refers to a primary key in another table (c) is always a picture (d) is a macro", "**(b).**"),
        ],
        trend="Data vs information, advantages of DBMS, definition of primary key.",
        onepager=["- Data raw; information processed.",
                  "- Database + DBMS (Base).",
                  "- Field, record, table.",
                  "- Primary key unique; foreign key links tables.",
                  "- DBMS: less redundancy, security, backup, sharing."],
        task=["On paper, design two tables Student(AdmNo PK, Name, Class) and Issue(IssueID PK, AdmNo FK, BookISBN, Date). Mark the keys."],
    ),
    ch(
        id="ch14-base-tables",
        num=14,
        title="Tables in LibreOffice Base",
        unit="dbms",
        unit_name="Part B · Database Management System",
        weight="part of 12 marks",
        short="Create tables in Design View, data types, primary key, field properties.",
        lede="The practical starts here. Design View + data types + PK is the 10-mark Base task.",
        lens=["Create a table with **four fields, correct types, PK set**.",
              "Field properties: Required, Length, Default, Format."],
        concepts=[
            "**1. Ways to create a table:** Design View (exam method), Wizard, View/SQL. Use **Design View**.",
            "**2. Data types:** Text [VARCHAR], Integer, Numeric/Decimal, Date, Time, DateTime, Yes/No, Memo (long text), Image (rarely).",
            "**3. Set primary key:** right-click the field → Primary Key (key icon). Save the table (`Student`).",
            "**4. Field properties:** Entry required (Yes), Length (25), Default value, Format example, AutoValue for integer PKs.",
            "**5. Datasheet view** is for typing records; Design View is for structure. Do not confuse them.",
            "**6. Save before closing.** Base will not keep an unsaved table design.",
            "**7. Good design:** one fact per field (separate FirstName, not a whole address in Name).",
        ],
        steps=["1. Base → Create Table in Design View.",
               "2. Type field names and data types down the rows.",
               "3. Right-click AdmNo → Primary Key.",
               "4. Set Length / Required as asked.",
               "5. Save as `Student`, then open Datasheet to enter two sample rows."],
        tricks=["- Phone numbers are **Text**, not Integer — or you lose leading 0.",
                "- Fees can be Decimal; age is Integer; DOB is Date."],
        mistakes=["- Forgetting to set the primary key — Base warns, some students click No.",
                  "- Using spaces in field names when the question gave `RollNo`."],
        qa=[
            qa("S", 2, "Name four data types in Base and one use each.",
               "VARCHAR for names, Integer for roll number, Date for DOB, Decimal for fees, Yes/No for paid flag."),
            qa("S", 2, "How do you set a primary key in Design View?",
               "Right-click the field row → Primary Key so the key icon appears, then save the table."),
            qa("L", 4, "Write field names, types and keys for a table Book.",
               "ISBN VARCHAR PK; Title VARCHAR; Author VARCHAR; Price DECIMAL; Available YES/NO. ISBN uniquely identifies a book; Available is Boolean."),
            qa("A", 3, "A student stores mobile numbers as Integer and 098… becomes 98. Why, and what type should be used?",
               "Integer drops leading zeros and is not a “number you calculate with”. Use **Text/VARCHAR**."),
            qa("C", 4, "Read and answer:\n\nTable Marks has fields Name, Marks, Marks, Date.\n\n(a) Three design faults.\n(b) Redesign with types and a PK.\n(c) Which view to use in the practical.",
               ["(a) Duplicate field name; no PK; Name is a weak key; Date of what?",
                "(b) StudentID INTEGER PK; Name VARCHAR; Marks INTEGER; ExamDate DATE.",
                "(c) Design View to build, Datasheet to enter records."]),
        ],
        mcq=[
            mcq("The exam-preferred way to create a table is: (a) Wizard only (b) Design View (c) Mail Merge (d) Goal Seek", "**(b) Design View.**"),
            mcq("DOB should be stored as: (a) Integer (b) Date (c) Yes/No (d) Image", "**(b) Date.**"),
            mcq("A primary key field should be: (a) empty often (b) unique and not null (c) a photo (d) duplicated", "**(b).**"),
            mcq("Datasheet view is for: (a) setting data types (b) entering records (c) recording macros (d) wrapping images", "**(b) entering records.**"),
        ],
        trend="Create-table steps, choice of data type, how to set PK.",
        onepager=["- Design View: fields + types + PK.",
                  "- Text for codes/phones; Date for dates; Decimal for money.",
                  "- Required / Length / Default.",
                  "- Datasheet = records; Design = structure."],
        task=["Create `Student(AdmNo INTEGER PK, Name VARCHAR(30), Class VARCHAR(5), Fees DECIMAL)` and enter three records."],
    ),
    ch(
        id="ch15-base-relationships",
        num=15,
        title="Relationships and Multiple Tables",
        unit="dbms",
        unit_name="Part B · Database Management System",
        weight="part of 12 marks",
        short="One-to-one, one-to-many, many-to-many; referential integrity.",
        lede="Two tables and a line between them. This is what separates Base from Calc.",
        lens=["Draw **one-to-many** (Student–Issue) with referential integrity.",
              "Know why we split tables (normalisation in simple words)."],
        concepts=[
            "**1. Why multiple tables:** store each fact once. Student details in Student; issues in Issue; link by AdmNo.",
            "**2. One-to-one:** one passport per citizen. Rare in Class 10 practicals.",
            "**3. One-to-many:** one student, many issue records. The **many** side holds the **foreign key**.",
            "**4. Many-to-many:** students and activities — needs a third (junction) table.",
            "**5. Creating a relationship:** Tools → Relationships → add tables → drag PK to FK → tick **Referential integrity** → optionally Cascade Update/Delete.",
            "**6. Referential integrity:** you cannot type an Issue.AdmNo that does not exist in Student. You cannot delete a student who still has issue rows (unless cascade).",
            "**7. Cascade update/delete:** changing/deleting the parent PK updates/deletes child rows. Use delete cascade only when the question asks.",
        ],
        steps=["1. Create both tables; set PKs.",
               "2. On the many side, add the FK field with the **same type** as the PK.",
               "3. Tools → Relationships.",
               "4. Drag Student.AdmNo to Issue.AdmNo.",
               "5. Tick Referential integrity → OK."],
        tricks=["- FK type must **match** PK type (both Integer, or both VARCHAR).",
                "- The crow’s-foot / many side is the table that **repeats** the key."],
        mistakes=["- Drawing the relationship backwards (PK on the many side).",
                  "- Different data types on PK and FK — Base refuses the link."],
        qa=[
            qa("S", 2, "What is a one-to-many relationship? Give an example.",
               "One record in table A matches many in table B. One student, many library issues. The Issue table stores AdmNo as FK."),
            qa("S", 2, "What is referential integrity?",
               "A rule that every foreign-key value must match an existing primary key, so you cannot create orphan records."),
            qa("L", 4, "Explain how to relate Student and Issue in Base.",
               "AdmNo PK in Student; AdmNo FK in Issue (same type). Tools → Relationships, drag PK to FK, enable referential integrity. Then an issue cannot use a missing admission number."),
            qa("A", 3, "A shop has Customer and Order tables. Where does CustomerID go, and what relationship is this?",
               "CustomerID is PK in Customer and FK in Order. One-to-many (one customer, many orders)."),
            qa("C", 4, "Read and answer:\n\nDeleting student 12 failed because “existing related records”.\n\n(a) What rule is firing?\n(b) Two safe ways to proceed.\n(c) When would cascade delete be wrong?",
               ["(a) Referential integrity — Issue rows still point to 12.",
                "(b) Delete or reassign the issue rows first; or (if asked) enable cascade delete.",
                "(c) When those issues are history you must keep — never cascade-delete library history by accident."]),
        ],
        mcq=[
            mcq("The foreign key is stored on the: (a) one side always (b) many side (c) report (d) form title", "**(b) many side.**"),
            mcq("Referential integrity prevents: (a) styles (b) orphan FK values (c) Goal Seek (d) macros", "**(b).**"),
            mcq("Student–Issue is typically: (a) one-to-one (b) one-to-many (c) many-to-many without a junction (d) no relation", "**(b) one-to-many.**"),
            mcq("Relationships window is opened from: (a) Tools → Relationships (b) Insert → Image (c) Format → Page (d) Data → Sort", "**(a).**"),
        ],
        trend="Define one-to-many + referential integrity; practical is drag-PK-to-FK.",
        onepager=["- Split data: one fact, one table.",
                  "- 1:1, 1:n, n:n (junction).",
                  "- FK on the many side, same type as PK.",
                  "- Referential integrity = no orphans."],
        task=["Build Customer(CustomerID PK) and Order(OrderID PK, CustomerID FK). Relate them with referential integrity and try to enter an order for a missing customer — it should fail."],
    ),
    ch(
        id="ch16-base-queries",
        num=16,
        title="Queries in Base",
        unit="dbms",
        unit_name="Part B · Database Management System",
        weight="part of 12 marks",
        short="Design View queries, criteria, sorting, aliases and related-table queries.",
        lede="A query asks a question of the tables. Criteria in the grid are the whole skill.",
        lens=["Practical: query with **two criteria and a sort**.",
              "Theory: what a query is, and examples of criteria (`>500`, `Like 'A*'`)."],
        concepts=[
            "**1. Query** = a saved question: which fields, from which tables, matching which criteria, in which order.",
            "**2. Create in Design View:** Queries → Create Query in Design View → add table(s) → double-click fields → set Sort and Criterion.",
            "**3. Criteria examples:** `Delhi` (exact text), `>75` (numbers), `<#01/01/2012#` or a date form, `Like 'A*'` (names starting with A), `IS EMPTY` / `IS NOT EMPTY`.",
            "**4. AND vs OR:** criteria on the **same row** = AND; on **different rows** = OR (in the design grid).",
            "**5. Alias:** field caption in the query (Marks → `IT Marks`) without renaming the table field.",
            "**6. Related tables:** add both tables (relationship line visible), pull Name from Student and Date from Issue.",
            "**7. Run:** click Run. Save the query as `QryToppers`. A query does not store a second copy of the data — it reads the tables live.",
        ],
        steps=["1. Queries → Create Query in Design View.",
               "2. Add Student, close the wizard.",
               "3. Add Name, Marks, Class.",
               "4. Criterion under Marks: `>=80`. Sort Marks Descending.",
               "5. Run, then Save."],
        formulas=["Marks >= 80",
                  "City = 'Delhi'",
                  "Name Like 'S*'",
                  "Fees BETWEEN 1000 AND 2000"],
        tricks=["- Text criteria need **quotes** in some modes; in the grid `Delhi` is often enough — follow what the lab build accepts.",
                "- `*` is the wildcard in Base Like patterns (not `%` as in some SQL)."],
        mistakes=["- Editing query results and expecting the table design to change.",
                  "- Forgetting to add the table so the field list is empty."],
        qa=[
            qa("S", 2, "What is a query in Base?",
               "A saved question that selects fields from one or more tables according to criteria and sort order, without storing a second copy of the data."),
            qa("S", 2, "Write criteria to list students whose names start with A and marks above 70.",
               "Name: `Like 'A*'` AND Marks: `>70` (same criteria row)."),
            qa("L", 4, "How do you create a query that shows student name and book title for issues after 1 Apr 2026?",
               "Design View → add Student, Issue, Book (related) → fields Name, Title, IssueDate → criterion on IssueDate `> {d '2026-04-01'}` or the date the lab uses → Run → Save."),
            qa("A", 3, "The librarian wants unpaid fees greater than 500, sorted by fees high to low. Which grid settings?",
               "Field Fees, criterion `>500`, Sort Descending; include Name/AdmNo so the rows are identifiable."),
            qa("C", 4, "Read and answer:\n\nA query saved last month still shows old marks after the teacher updates the table.\n\n(a) Is that expected?\n(b) Why?\n(c) When would you use a Wizard instead of Design View?",
               ["(a) No — a select query should show current table data when run again.",
                "(b) Queries read tables live; if it does not update, they opened an old copy or a static export.",
                "(c) Wizard for a simple one-table list; Design View when you need criteria, sorts and two tables."]),
        ],
        mcq=[
            mcq("A query stores: (a) a second full copy of all data always (b) the question (fields, criteria) (c) a Writer template (d) an OS", "**(b).**"),
            mcq("Names starting with R use: (a) Like 'R*' (b) = R (c) Group (d) F11", "**(a) Like 'R*'.**"),
            mcq("Two criteria on the same row mean: (a) OR (b) AND (c) XOR (d) NOT a query", "**(b) AND.**"),
            mcq("To sort marks highest first: (a) Sort Ascending (b) Sort Descending on Marks (c) Primary key (d) Wrap Optimal", "**(b).**"),
        ],
        trend="Write a criterion, or steps of Design View query.",
        onepager=["- Query = live question, not a second database.",
                  "- Design View: tables → fields → criterion → sort → Run.",
                  "- Same row AND; extra row OR.",
                  "- Like 'A*', >75, dates, BETWEEN."],
        task=["On Student, create `QryHonours`: Name, Marks where Marks>=80, sort Marks desc. Run it after changing one mark to see it update."],
    ),
    ch(
        id="ch17-base-forms-reports",
        num=17,
        title="Forms and Reports",
        unit="dbms",
        unit_name="Part B · Database Management System",
        weight="part of 12 marks",
        short="Data-entry forms and printable reports from tables or queries.",
        lede="Form = type data; Report = print data. Wizards are allowed; know what each control is.",
        lens=["Practical often: **form on Student** + **report from a query**.",
              "Theory: difference between form and report; one advantage each."],
        concepts=[
            "**1. Form:** on-screen layout for entering and editing records, one at a time, with labels and controls. Safer than raw datasheet (validation, no extra columns).",
            "**2. Create:** Forms → Use Wizard to Create Form → pick fields → arrange (columnar) → set subform if needed → name `frmStudent`.",
            "**3. Controls:** text box, list box, check box, label, button. Label is the caption; the text box is bound to a field.",
            "**4. Report:** formatted output for printing / PDF — headers, grouping, totals. Built from a table or (better) a query.",
            "**5. Create:** Reports → Wizard → fields → grouping (e.g. by Class) → sort → layout → name `rptFees`.",
            "**6. Why a query under a report:** filter first (only unpaid fees), then print. Changing the query criteria changes the report next time you open it.",
            "**7. Form vs report:** form is **interactive input**; report is **read-only output**.",
        ],
        steps=["Form wizard: select table → fields → display (columnar) → data-entry only if asked → finish.",
               "Report wizard: select query → fields → group by Class → sort Name → add sum of Fees if asked → finish."],
        tricks=["- If the report is empty, the **query returned zero rows** — fix criteria first.",
                "- Name forms `frm…` and reports `rpt…` so the examiner finds them."],
        mistakes=["- Building a report on the whole table when the question said “students with marks > 80”.",
                  "- Using a form to print 200 rows — that is a report’s job."],
        qa=[
            qa("S", 2, "Differentiate a form and a report.",
               "A **form** is for entering/editing records on screen. A **report** is a formatted, usually read-only printout or PDF of selected data."),
            qa("S", 2, "Why create a report from a query rather than from a whole table?",
               "The query filters and sorts first (e.g. only unpaid fees), so the report prints exactly the needed rows."),
            qa("L", 4, "Write steps to create a data-entry form for the Student table in Base.",
               "Forms → Use Wizard → table Student → select fields → choose layout (columnar) → set to display all data / data entry → style → name `frmStudent` → finish. Test by adding one record."),
            qa("A", 3, "The office wants a printed list of Class 10 students owing more than ₹500, grouped by section. Form or report? What sits underneath?",
               "A **report**. Underneath: a query with Class=10, Fees>500, then group by section in the report wizard."),
            qa("C", 4, "Read and answer:\n\nData-entry staff keep typing in Datasheet and accidentally delete a column.\n\n(a) Which object reduces that risk?\n(b) Two reasons.\n(c) How should monthly printouts be produced?",
               ["(a) A form with only the needed controls.",
                "(b) No access to Design View; labels guide the operator; validation.",
                "(c) A report (from a query), not a screenshot of the datasheet."]),
        ],
        mcq=[
            mcq("A form is mainly for: (a) printing totals (b) entering and editing records (c) recording macros (d) 7 Cs", "**(b).**"),
            mcq("A report is mainly for: (a) typing new rows (b) formatted output/print (c) setting OS password (d) wrapping images", "**(b).**"),
            mcq("The best source for a filtered report is: (a) a query (b) a random image (c) Track Changes (d) a template .ott", "**(a) a query.**"),
            mcq("A check box on a form suits a: (a) Yes/No field (b) photo of the school (c) Goal Seek cell (d) Heading 1 style", "**(a) Yes/No field.**"),
        ],
        trend="Form vs report, or wizard steps; practical is one of each.",
        onepager=["- Form = input UI; Report = printout.",
                  "- Wizards are allowed; name frm / rpt.",
                  "- Report from a query for filters and sorts.",
                  "- Grouping and totals belong on reports."],
        task=["Create `frmStudent` (columnar) and `rptHonours` based on `QryHonours`. Print-preview the report."],
    ),
    ch(
        id="ch18-workplace-safety",
        num=18,
        title="Health, Safety and Security at the Workplace",
        unit="safety",
        unit_name="Part B · Healthy, Safe and Secure Working Environment",
        weight="part of 10 marks",
        short="Hazards, occupational health, electrical and fire safety, security of data.",
        lede="Unit 4 is definition-plus-example. Hazards and electrical safety are the core.",
        lens=["**10 marks with the rest of Unit 4.** Hazard types + two precautions each.",
              "Data security is part of this unit in the current curriculum — passwords, backups, authorised access."],
        concepts=[
            "**1. Hazard** = anything that can cause harm. **Risk** = chance that the harm will occur.",
            "**2. Types of hazard:** physical (cables, noise, fire), electrical, chemical (cleaner fumes), biological, ergonomic (bad chair), psychosocial (stress, bullying).",
            "**3. Occupational health:** physical and mental wellbeing at work. Fatigue, eye strain and RSI are IT-lab issues.",
            "**4. Electrical safety:** no overloaded sockets, no frayed wires, dry hands, don’t open the SMPS, use earthed plugs, UPS/surge protector.",
            "**5. Fire:** know exits, don’t block them, switch off power, use the **correct extinguisher** (CO2 / dry powder on electrical — not water).",
            "**6. Security:** lock the lab, visitor register, don’t share passwords, lock the screen, authorised software only, backup.",
            "**7. Policy / responsibility:** follow school/lab rules, report hazards, use equipment as trained. Employers provide a safe workplace; employees cooperate.",
        ],
        tricks=["- Water on an electrical fire is the classic **wrong** answer.",
                "- Hazard vs accident: hazard is the **potential**; accident is the **event**."],
        mistakes=["- Writing “be careful” with no concrete precaution.",
                  "- Mixing this unit with the old “Web Applications and Security” syllabus."],
        qa=[
            qa("S", 2, "Differentiate a hazard and an accident with an IT-lab example.",
               "A **hazard** is a potential source of harm (a loose cable across the aisle). An **accident** is the event (a student trips and the monitor falls)."),
            qa("S", 2, "List four electrical safety rules for a computer lab.",
               "Dry hands; earthed plugs; no overloaded boards; don’t open the power supply; report frayed wires; use a surge protector."),
            qa("L", 4, "Explain four types of workplace hazard with one IT-lab example each.",
               "Physical — trailing cables; electrical — open socket; ergonomic — low screen causing neck pain; psychosocial — long hours without a break. Control each: cable covers, close sockets, raise the monitor, timetable breaks."),
            qa("A", 3, "A student pours water on a sparking socket. Two mistakes and the correct actions.",
               "Water on electrical fire; staying next to a live spark. Instead: don’t touch, switch off mains if safe, alert staff, use CO2/powder extinguisher, evacuate."),
            qa("C", 4, "Read and answer:\n\nLab PCs face a window, chairs don’t adjust, passwords are on sticky notes.\n\n(a) Name three hazard/security issues.\n(b) One control for each.\n(c) Who should you report this to?",
               ["(a) Glare (ergonomic), poor posture, password leak (security).",
                "(b) Blinds/position screens, adjustable chairs, unique passwords stored in a password manager / teacher vault — never sticky notes.",
                "(c) Lab teacher / system admin / safety in-charge."]),
        ],
        mcq=[
            mcq("A trailing cable is mainly a: (a) 7 C (b) physical hazard (c) query (d) style", "**(b) physical hazard.**"),
            mcq("On an electrical fire you should not use: (a) CO2 (b) dry powder (c) water (d) the alarm", "**(c) water.**"),
            mcq("RSI in a data-entry job is mostly: (a) a green job (b) an ergonomic/occupational health issue (c) a primary key (d) mail merge", "**(b).**"),
            mcq("A sticky note under the keyboard with the password is a failure of: (a) ToC (b) data security (c) Goal Seek (d) grouping", "**(b) data security.**"),
        ],
        trend="Hazard types, electrical/fire rules, or password/backup security.",
        onepager=["- Hazard = potential; accident = event; risk = chance.",
                  "- Types: physical, electrical, chemical, biological, ergonomic, psychosocial.",
                  "- Electrical: dry, earthed, no overload; never water on electrical fire.",
                  "- Security: locks, passwords, authorised access, backup."],
        task=["Walk your computer lab and list five hazards with one control each. Include at least one electrical and one ergonomic."],
    ),
    ch(
        id="ch19-quality-ergonomics",
        num=19,
        title="Workplace Quality and Ergonomics",
        unit="safety",
        unit_name="Part B · Healthy, Safe and Secure Working Environment",
        weight="part of 10 marks",
        short="Quality of work, 5S, housekeeping, ergonomic posture and workstation setup.",
        lede="Sit right, arrange the desk, and 5S the lab. This is the “quality measures” chapter.",
        lens=["**Ergonomics of a computer workstation** is the set diagram/answer.",
              "5S (Sort, Set in order, Shine, Standardise, Sustain) appears as a 2-mark list."],
        concepts=[
            "**1. Quality of work** in IT: accurate data, readable documents, meeting time, following the house style, checking before submit.",
            "**2. Housekeeping:** clear aisles, labelled cables, no food, bags not in walkways, shut down PCs.",
            "**3. 5S:** Sort (remove extra), Set in order (a place for everything), Shine (clean), Standardise (same method), Sustain (habit).",
            "**4. Ergonomics** designs work to fit the person. Goal: reduce strain, errors and fatigue.",
            "**5. Workstation:** feet flat, knees ~90°, back supported, screen top at eye level, screen an arm’s length away, elbows ~90°, mouse next to keyboard, wrists straight.",
            "**6. 20-20-20 rule:** every 20 minutes look at something 20 feet away for 20 seconds — reduces eye strain.",
            "**7. Lighting and noise:** no glare on screen, enough light to read paper, headphones or quiet for data-entry accuracy.",
        ],
        tricks=["- Screen **top at eye level**, not looking down at a laptop on the lap.",
                "- 5S order is asked as a list — don’t shuffle Shine and Sort."],
        mistakes=["- Drawing the user hunched over a laptop as “correct posture”.",
                  "- Defining quality as “working fast” with no accuracy."],
        qa=[
            qa("S", 2, "What is ergonomics? Give two workstation rules.",
               "Designing work to fit the person. Rules: screen at eye level, feet flat, back supported, wrists straight, mouse beside the keyboard."),
            qa("S", 2, "Expand 5S.",
               "Sort, Set in order, Shine, Standardise, Sustain."),
            qa("L", 4, "Describe a correct computer workstation and two quality checks before submitting a practical file.",
               "Chair and desk so elbows and knees are about 90°, screen arm’s length, top at eye level, no glare. Quality: proof-read, spell-check, file named as asked, print preview, backup copy."),
            qa("A", 3, "Amit’s laptop is on a high table, he looks up, and his wrists bend on the edge. Two injuries this invites and two fixes.",
               "Neck strain and wrist RSI. Fixes: raise the chair or lower the desk, laptop stand + external keyboard, wrist straight, breaks."),
            qa("C", 4, "Read and answer:\n\nA lab has tangled wires, unmarked CDs, glare, and students skip spell-check.\n\n(a) Map each problem to 5S or ergonomics or quality.\n(b) One action each.\n(c) Why quality matters in a data-entry job role.",
               ["(a) Wires/CDs → 5S Set in order; glare → ergonomics; skip spell-check → quality.",
                "(b) Cable ties + labels; blinds or move screens; compulsory preview + peer check.",
                "(c) Wrong data costs money and trust — the job role is Domestic Data Entry Operator."]),
        ],
        mcq=[
            mcq("The first S in 5S is: (a) Shine (b) Sort (c) Sustain (d) Speed", "**(b) Sort.**"),
            mcq("Screen top should be: (a) at knee level (b) at eye level (c) behind you (d) on the floor", "**(b) at eye level.**"),
            mcq("20-20-20 is for: (a) macros (b) eye strain (c) primary keys (d) mail merge", "**(b) eye strain.**"),
            mcq("Quality in data entry mainly means: (a) speed only (b) accuracy and completeness as well as speed (c) colourful fonts (d) loud music", "**(b).**"),
        ],
        trend="5S list or workstation posture; sometimes 20-20-20.",
        onepager=["- Quality = accurate, complete, on time, checked.",
                  "- 5S: Sort, Set in order, Shine, Standardise, Sustain.",
                  "- Ergonomics: 90° elbows/knees, screen eye-level, arm’s length.",
                  "- 20-20-20 for eyes."],
        task=["Photograph or sketch your study desk. Mark three ergonomic faults and the fix for each."],
    ),
    ch(
        id="ch20-accidents-emergencies",
        num=20,
        title="Prevent Accidents and Emergencies",
        unit="safety",
        unit_name="Part B · Healthy, Safe and Secure Working Environment",
        weight="part of 10 marks",
        short="Causes of accidents, evacuation, first aid, emergency numbers and incident reporting.",
        lede="Last chapter of IT 402. Evacuation steps and first aid for cuts, burns and shock.",
        lens=["**Evacuation order** and **first aid don’ts** are the 2–3 markers.",
              "Know: assembly point, don’t use lifts, report incidents even if small."],
        concepts=[
            "**1. Causes of accidents:** unsafe conditions (wet floor, bad wiring) and unsafe acts (running, bypassing rules). Most lab accidents are preventable.",
            "**2. Prevention:** training, PPE where needed, maintenance, 5S, no horseplay, report near-misses.",
            "**3. Emergency types:** fire, electric shock, medical, earthquake, data breach.",
            "**4. Evacuation:** alarm → save work if safe and seconds allow → leave bags → nearest **stairs**, not lift → assembly point → headcount → don’t re-enter.",
            "**5. First aid principles:** protect yourself, call for help, don’t move a seriously injured person, CPR only if trained, cool a burn with water (not ice/toothpaste), for shock switch off power **before** touching.",
            "**6. Electric shock:** switch off mains, use a non-conductor to separate, call help, recovery position if breathing.",
            "**7. Reporting:** date, time, place, names, what happened, injuries, witnesses, action taken. Near-misses count — they prevent the next accident.",
            "**8. Numbers:** school office, local fire, ambulance 112 (India emergency). Keep them posted in the lab.",
        ],
        tricks=["- **Power off before touch** is the electric-shock line examiners want.",
                "- Near-miss reporting is a quality/safety behaviour, not “telling on someone”."],
        mistakes=["- Applying toothpaste or ice directly on a burn.",
                  "- Using the lift during a fire drill."],
        qa=[
            qa("S", 2, "List four steps of evacuation in the correct order.",
               "Hear the alarm → leave via stairs (not lift) → go to the assembly point → answer the headcount and wait for the all-clear."),
            qa("S", 2, "Why report a near-miss?",
               "A near-miss shows a hazard that almost caused harm. Reporting it lets the school fix the condition before someone is actually injured."),
            qa("L", 4, "Explain first aid for (i) a small cut (ii) a minor burn (iii) suspected electric shock.",
               "Cut: wash, pressure, clean dressing. Burn: cool with running water 10 minutes, loose sterile cover, no toothpaste/ice. Shock: do not touch until power is off; then separate with a dry non-conductor, call help, monitor breathing."),
            qa("A", 3, "The fire alarm rings. A student runs back for a USB and takes the lift. Two wrong actions and the correct ones.",
               "Going back for belongings and using the lift. Correct: leave immediately by stairs, USB can be replaced, assemble for headcount."),
            qa("C", 4, "Read and answer:\n\nDuring a practical a student gets a shock from a damaged mouse cable, laughs it off, and no one writes it down.\n\n(a) Immediate first actions.\n(b) Why a report still matters.\n(c) Two prevention steps so it does not recur.",
               ["(a) Switch off power, check breathing, first aid, inform the teacher.",
                "(b) Near-miss/incident record → cable replaced, others warned, pattern spotted.",
                "(c) Inspect peripherals, remove damaged devices, remind: report all shocks."]),
        ],
        mcq=[
            mcq("During a fire, do not: (a) use stairs (b) go to the assembly point (c) use the lift (d) follow the teacher", "**(c) use the lift.**"),
            mcq("For electric shock, first: (a) grab the person (b) switch off power (c) pour water (d) apply toothpaste", "**(b) switch off power.**"),
            mcq("A near-miss should be: (a) ignored (b) reported (c) punished always (d) posted on social media", "**(b) reported.**"),
            mcq("A minor burn is cooled with: (a) ice cubes rubbed hard (b) running water (c) toothpaste (d) cotton oil", "**(b) running water.**"),
        ],
        trend="Evacuation steps or electric-shock first aid; near-miss as a value item.",
        onepager=["- Accidents = unsafe act + unsafe condition; prevent both.",
                  "- Evacuation: alarm, stairs, assembly, headcount.",
                  "- Shock: power off, then help. Burns: water, not toothpaste.",
                  "- Report incidents and near-misses. Emergency 112."],
        task=["Write a half-page incident report for a fictional wet-floor slip in the lab: who, when, where, injury, action, prevention."],
    ),
])


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    groups = {
        "01-employability.json": [c for c in CHAPTERS if c["unit"] == "pa"],
        "02-writer.json": [c for c in CHAPTERS if c["unit"] == "writer"],
        "03-calc.json": [c for c in CHAPTERS if c["unit"] == "calc"],
        "04-dbms.json": [c for c in CHAPTERS if c["unit"] == "dbms"],
        "05-safety.json": [c for c in CHAPTERS if c["unit"] == "safety"],
    }
    for name, items in groups.items():
        path = OUT / name
        path.write_text(json.dumps(items, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {path.relative_to(OUT.parent.parent.parent.parent)} ({len(items)} chapters)")
    print(f"total {len(CHAPTERS)} IT 402 chapters")


if __name__ == "__main__":
    main()
